run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - gocritic

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/oceanmining/game-manager
  gocritic:
    disabled-checks:
      - exitAfterDefer

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
